import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          INTERACTIVE HTML5 DIGITAL PUBLISHING PLATFORM FLIPHTML5.COM
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="European Travel Destinations" />
        <meta property="og:type" content="article" />
        <meta
          property="og:image"
          content="http://euro-travel-example.com/thumbnail.jpg"
        />
        <meta
          property="og:url"
          content="http://euro-travel-example.com/index.htm"
        />
      </Head>

      <main className={styles.main}>
        <h1>share page meta tags for messages</h1>
        <h1>get relative url javascript</h1>
      </main>
    </div>
  );
}
